### ISSUE TITLE
Can't build solution

### ISSUE THREAD

**Issue by TranBaVinhSon** [FrancescoBonizzi/Xls2Pdf#1]
Sorry for my naive question, I'm new with `C#` ecosystem.
when I run `dotnet build -c release` at `Xls2Pdf\Xls2Pdf` folder, I got this error:

> C:\Program Files\dotnet\sdk\3.0.100\Microsoft.Common.CurrentVersion.targets(3056,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\3.0.100\MSBuild.exe" exists and can be run. [C:\Users\test-admin\Programming\Xls2Pdf\Xls2Pdf\Xls2Pdf.csproj]

Please help me if you have time! Many thanks.

**Comment by FrancescoBonizzi** [comment]
Hi Tran!

I think you `dotnet build` relies to .NET Core 1.x and later versions, but this project is coded with .NET Framework, which can build only on Windows. 

Which is your environment? OS, IDE...?

**Comment by TranBaVinhSon** [comment]
Hi, Im using Visual Code 2019 on Window server 2016!

**Comment by FrancescoBonizzi** [comment]
Can you try with Visual Studio 2019 instead of Visual Studio Code? Because this application has the GUI developed with WPF which I think in this moment isn't available in Visual Studio Code. When you install Visual Studio 2019 remember to add the "Desktop development" package.

Let me know!

**Comment by TranBaVinhSon** [comment]
Sorry for my typo. I'm using Visual Studio 2019 and I already installed `Desktop development`. But I still  got the above error: 
> C:\Program Files\dotnet\sdk\3.0.100\Microsoft.Common.CurrentVersion.targets(3056,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\3.0.100\MSBuild.exe" exists and can be run. [C:\Users\test-admin\Programming\Xls2Pdf\Xls2Pdf\Xls2Pdf.csproj]
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.

**Comment by FrancescoBonizzi** [comment]
Ok, no problem! Have you tried to build with Visual Studio, instead of manually using the command line?

![image](https://user-images.githubusercontent.com/11348479/69948814-90119780-14f0-11ea-9aab-bb78667ee1a4.png)

**Comment by TranBaVinhSon** [comment]
Yeah, `dotnet build -c release` doesn't work with .NET Framework. 
Your application is working very well,
Many thanks ! 🙇

**Comment by FrancescoBonizzi** [comment]
I'm happy! :-)

**Comment by TranBaVinhSon** [comment]
@FrancescoBonizzi Thanks for your support. I really appreciate. I just want to ask that `Microsoft.Office.Interop.Excel` is only working with `.NET Framework` or it can work on `.NET Core`.  Thanks in advance!

**Comment by TranBaVinhSon** [comment]
@FrancescoBonizzi And sorry for my other question. It seems like your application works well even with `Excel 2019`. If I build a web api to convert excel to pdf (using .NET framework), do I need to install `Excel 2013` instead of `Excel 2019` in order to use `Microsoft.Office.Interop.Excel` package ?
